### ISSUE TITLE
Deploy the email sending service

### ISSUE THREAD

**Issue by sreenath004** [arunmr1980/aws-email-service#5]
- Deploy the email sending service available here
 (https://github.com/arunmr1980/aws-email-service)

**Comment by arunmr1980** [comment]
Email service is deployed and working. To send email send that to 'EmailSNSTopic'

Attachments not supported yet.

### Sample request

```
{
  "from": "arun.mr@scottsdaleglobal.com",
  "to_addesses": ["merry.arun@gmail.com", "strider.galaxies@gmail.com"],
  "title": "Email Service Test [SNS Trigger]",
  "body_html": "<p>Blah Blah</p>",
  "body_text": "Blah Blah"
}
```

Note that email ids needs to be verified in SES
